Use the data loans_income.csv to do listed practice:

Read the data in pandas, 
1. Draw a sample with 1000 observations.
2. Implemented bootstrap to take 10, 50 , 100, 1000 times resampling to repeatedly draw a income sample with 10 incomes
3. Implemented bootstrap to take 10, 50 , 100, 1000 times resampling to repeatedly draw a income sample with 100 incomes

## Sample with 1000 observations

In [1]:
import pandas as pd
df=pd.read_csv("loans_income.csv")

In [6]:
sample=df.sample(n=1000)

## Bootstrap with 10 incomes

In [14]:
#Bootstrap of 10 times
sample_props = []
for _ in range(10):
    sample = np.random.choice(df.x, size=10)
    print(sample)

[ 43000  73000 138082  45000  45000  57000 110000  45000  82000  65000]
[ 75000 115000  45000  87000  37000  84000 110004 108000  34000  80000]
[ 62300  75000  48000  80000  36120  65000  68000  82000  46000 105000]
[30160 55000 48000 65000 73000 51000 84000 62000 53000 96000]
[104000 110000  55000 135000  55528  50000  30000  63000  70000  59058]
[ 90000  50000 115000 145000  47000  51000  38000  40900  40000  60000]
[47000 32000 28000 25000 90000 35000 82000 42057 46000 63000]
[ 30000  90000  89000  60000  58000  55000  65000 110000 105000  60000]
[70000 65000 78000 21600 75000 30000 34000 80004 78000 78400]
[111000  65000  60000  87000  78000  90000  54000  45000 105000  50666]


In [15]:
#Bootstrap of 50 times
sample_props = []
for _ in range(10):
    sample = np.random.choice(df.x, size=10)
    print(sample)

[ 40000  50000  85000  52000  65000 112000  40000  50457  42000  55000]
[ 31000 119000 122000  56000  95000  40000  40000  51000  50000  58000]
[ 50800 110000  28000  80000  72000  46000  55000 102000 149000  80000]
[ 54996  64000  60000  69000  80000  57700  57219 115000  80000  18000]
[ 48619  60000  58342  88000  71800  95000  96000 110000  60000  75000]
[ 50000  50000  80000 119000  68500  80000  55000  75000  38500  11029]
[129000  47000  45000 140000 110000  64800  75000  22000 120000  72000]
[110000  65000  85242  51000  47000 125000  75000  36000  56000  73000]
[145000  45000  45000  37000  64000  76000  82000  53400  67500  55500]
[ 25104  77000  36000  48000  80000 100000 100000  25000  50000  41600]


In [16]:
#Bootstrap of 100 times
sample_props = []
for _ in range(10):
    sample = np.random.choice(df.x, size=10)
    print(sample)

[ 28945  50000  40000  94000  54500  84000 112000  75000  47000  71250]
[78000 37000 16000 51000 24556 89000 85000 89000 78000 62000]
[38000 40000 69839 48000 55000 40000 38000 49500 50400 46000]
[ 65000  55000  72000  50000  25000  50000  98000  85000  41184 115000]
[36000 36000 45000 70000 25896 99000 60000 21840 50000 38000]
[191000 140000  34000  55000  53000  54000  61000  65000  80000  49000]
[62000 67000 18600 10000 70000 55000 34000 62000 90000 80000]
[ 40188  40000  74400 105000  89200  56000  45000  26000  85000  41000]
[ 75000  80000  55000  50000 115000  82000 160000  24000 144000  36000]
[100000  61027  33300  50000  43000 131053  40000 128000  59500 109000]


In [17]:
#Bootstrap of 1000 times
sample_props = []
for _ in range(10):
    sample = np.random.choice(df.x, size=10)
    print(sample)

[ 95000  24000  50000  35000 112500  33000  41000  70000  55000 101000]
[ 44500  85000  50000  77000  34000 105000  27000  85000  64962 140000]
[106000  55000  65000 113000  53000 130000 117000  35000  70000  90000]
[ 78000  12996  57000  55000  35656 105000  85000  78800  53000  40000]
[ 25000  12000  32000 130000  82000  56035  16800  65000 118000  86000]
[116000  78000  16440  62000  90000  50000  78996  38000  99000  45000]
[34800 85000 35000 67000 40000 70000 37995 32000 48000 80000]
[63300 75000 50000 77000 26000 50000 90000 46536 60000 54000]
[ 40000  26000  44507  85000 170000  45000  44800  43000  85000  60000]
[55000 59728 65000 65000 26000 35000 30000 62000 32000 99000]


## Bootstrap with 100 incomes

In [18]:
#Bootstrap of 10 times
sample_props = []
for _ in range(10):
    sample = np.random.choice(df.x, size=100)
    print(sample)

[ 52000 100000  31000  65000  56000  92000  39992 150000  62000  75000
  85000 120000  41000  95000  65000 110000  38000  76000  25000  68000
  78506  72000  93000  65000  40000  54000  41000 150000  90300  80000
  36000  89450 129000  65000  40000 150000  85000  37873  65000  55500
 185000  55000  31000 104000 154008  98000  65800  90000  43000  99167
  75000  86000  60000 153816  30000  58000  84000 120000  81000  72000
  66000 100000  50000  30953 109000  31000  48000  55000  12000  28800
  43000  85000  46925  40000  99700  47000  59295  39000  52852  51000
  32000 155000  53000  64000  51000  80000  38000  55000 150000  96000
  39600  33000  60300  40000  70000  48000  49000  60000  85000 125000]
[ 50000  40000 105000 120000  48000  57240 100000  57000  35000  40000
  70000  31000  35000 119000  53000  20000  36000  43000  50000  43000
  90000  98268  80000  75000  50000  28920 115000 144000 115000 125000
  80000  51000  62000  72000 129600  66000 155478  72000  32000  25000
  350

In [19]:
#Bootstrap of 50 times
sample_props = []
for _ in range(10):
    sample = np.random.choice(df.x, size=100)
    print(sample)

[ 92000  45000  48000  95000  39000  80000  64000  28500  56600  45000
 160000  76000  41000  55000 171000  45000  28000 120000  45000  56600
  40000 100000 160000  10000  55600  52000  75000  13200  32000  35000
  75000  56000 104000  64000  85000  30000  60000  67800 169500  79000
  75000  57000  50000  40000  79000 104000  53000 150000  24000 102000
  73000  42000 112000  35000  78000 180000  85000  85000  32760  53600
 115000  40000 120000  58000  48609  80000 142000 106080  42557  82000
  51000  30000  35000  84000  42000  26000  42000  42000  52500  87000
 160000  92000  45000  56000  55000  51600  50000  55000  84892  62004
  17000  57000  46000 117400  77000  20000 121571  80000  65000  51200]
[190000  70000  30000  32000 101108  85000  37397  44000  75689  88000
  42000  65000  80000  90000  62400 137000  48900  29000  72540 110000
  95000  45000  28080  63000  50000  60675  43000 180000  78300  64000
  37000  92000 115000  40000 175000  80000  80000 102000 105261  50000
  548

In [20]:
#Bootstrap of 100 times
sample_props = []
for _ in range(10):
    sample = np.random.choice(df.x, size=100)
    print(sample)

[ 52000  39996  43000  29152  88000  35000  59550  22000  70000  26000
  87000  78000  60000  65500  56964  52000  41700  49000  45000  40000
  54814  75000  70000  50000  43000  50000  29000  70000  42000  80000
  73000  29000  40000 103000  42000 110000 100000 102000  36000  72000
 124644  90450  45000  90000  60000  31000  43000  33000  28000  80000
  39520  44000  46004  56000  70000  42000 112000  78000  72000  70000
  65000 120000  95000 110000  35000  42000  42550  58000 165000  68550
 100000  42000 115000 170000  52000  47748  35000  38000 150000  45000
  49899  90000 120000  68000  62000 120000  78695  62000  39051  38000
  60000  40000  28000  90000  92000  85000  36000  26300  95000  60000]
[100000  90000  33000 126000  50250 105000 190000 110000  64000  38000
  32000 102000 100000  32000  51000  42000 100000  33000  55000  98000
  76600  60000  70000 110000  36000  39000 108000  56400  60000  70000
 115572  38000  70000  70000  28128 160842  40000  25000  33000  41000
  700

In [21]:
#Bootstrap of 1000 times
sample_props = []
for _ in range(10):
    sample = np.random.choice(df.x, size=100)
    print(sample)

[ 89000  40000  33000  85000 110000  55000 113000  72000 106000  42000
  45000  92000  40000  80500 175000  35000  96000 108000  86000  32000
  52000 100000  45275  50000  49000  30000  65000  52000  80000 120000
  30000  68000  45000  45000  34000  59207 120000 110000  95000 175000
  75000  51000 114000  50000  35000  24000  40000  40000 110000  75000
  48000  69000 120000 100000 103000 100000 140000  40000  33000  68000
  97000  87000  72664  30000  70000  41600  25000  60000  60000  37000
  80000  40000  73196 140000  81600 115000  66000 104000  62000  47000
  50004  58500  95000  62000  50000 140000  80300  67846  38500  92700
  68000  76000  35000  40000  35000  48000  51000  70000  70000  34500]
[ 30000  26000 150000  92508 100000  45000  45000 150000  71000  80000
  75000  38000 123000  27000  80000  87000  75000  31000  40000  55000
  63000  42000  81000  10000  65000  75573  62695  48000  86000  41000
  71500  50000  85000  45000  80000 102000  60000 105000 150000  50000
  280